---
title: Bachelor Course on Functional Programming
---
#+STARTUP: showeverything
#+title: Bachelor Course on Functional Programming
#+language:    'en'

This course introduces *functional programming* through the
programming language Haskell. In contrast with the language C# --
introduced in Imperatief/Game/Mobiel programmeren -- which is based
on statements, organized in methods and classes, functional
programming is based entirely on expressions and functions. This
shifts the focus from /how/ a program operates to /what/ it does.

Concrete topics treated in this course include higher-order functions,
parametric and ad-hoc polymorphism (also known as generics and
overloading in other programming languages), algebraic data types and
pattern matching. These ideas appear not only in Haskell, but in other
modern languages such as Scala, Swift or Kotlin. An important part of
the course is devoted to /reasoning about programs/, either by
equations or by induction.

The language Haskell imposes a strong separation between pure
computations and those with /side-effects/, such as input and
output. /Monads/ are introduced to model the idea of sequential
computation in a functional language. Similar abstractions such as
/functors/ are also part of the contents of this course.


- Lecturers :: [[mailto:m.i.l.vakar@uu.nl][Matthijs Vákár]] and [[mailto:F.Staals@uu.nl][Frank Staals]]

  For any enquiry about the course, please mention [INFOFP] in the title.

* Teaching Objectives

By the end of the course you will be able to

+ solve problems using a 'functional approach'. That is, define /what/
  needs to be computed using techniques and concepts such as
    - recursion,
    - pattern matching,
    - composition,
    - higher order functions,
    - algebraic data types,
    - monads,
    - immutable and persistent data structures, and
    - laziness.
+ reason about the correctness and the types of functions.
+ develop a small, real world game in the functional language Haskell.

* Announcements

*** 2021-09-02 : GHC Installation Instructions

  Unfortunately, installing "Haskell" is often somewhat
  troublesome. The instructions for this year in the [introduction
  practical assignment](practicals/Assignment0.pdf) suggest that you
  install GHC through a tool called "stack" that you will need for the
  final project. Alternatively, you can install GHC directly. Last
  year, Jip, one of our TAs, has written detailed instructions on how
  he set up his windows machine for Haskell development. You can find
  his guide [here](practicals/windows_instructions.pdf).

  For OS X (High Sierra or newer)
  [these](https://medium.com/@dogwith1eye/setting-up-haskell-in-vs-code-on-macos-d2cc1ce9f60a)
  detailed instructions on how to set up your system may be useful.

* Schedule

There are weekly [[lectures.html][lectures]] (2 × 2 hour), [[exercises.html][instructions]] (1 × 2 hour) and
[labs.html][practicals] (1 × 2 hour). Attendance is not strictly
mandatory (albeit strongly recommended).

*You are expected to work on your own in addition to these hours!*

The lectures, instructions, and practicals typically take place at the
Utrecht Science Park ('de Uithof'). In particular, the weekly schedule
is:

[[./images/week_schedule.svg]]

* Literature

- Required reading: [[http://www.cs.nott.ac.uk/~pszgmh/pih.html][Programming in Haskell]] by Graham Hutton

- Additional material:
    - [[http://www.cs.uu.nl/people/jur/FP-elec.pdf][Lecture Notes from 2015/2016]], mostly in Dutch
    - [[http://learnyouahaskell.com/][Learn You a Haskell for Great Good]] by Miran Lipovača
    - [[https://en.wikibooks.org/wiki/Haskell][Haskell Wikibook]]

* Exams

There will be a midterm and a final exam.

* Assignments

There are two kinds of *mandatory* assignments:

- [[labs.html][Practical assignments]] pose programming problems with the aim of
  practicing your Haskell skills. These assignments are automatically
  corrected by [[https://domjudge.cs.uu.nl/dj/fp/team/][DOMJudge]]. You can ask any of the teaching assistants to
  suggest improvements to your code style during labs sessions.
- The [[labs.html][final programming project]] consists of programming a small game
  in Haskell. The code is graded for correctness, design and style.

In addition to those mandatory assignments, there is an *optional*
assignment to be made in groups to get some extra points in the
grade. The assignment involves exploring and presenting some [[https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/lang.html][language
extension]] or [[http://hackage.haskell.org/][Haskell library]].


* Grading

The final grade depends on the two exams and the assignments.

- The *theory* grade is T = 0.3 × grade of mid-term + 0.7 × grade of
  final exam.

  - CT :: You need T >= 5 to pass the course.

- The *practical* grade is P is grade of final programming
  project (The game).

  - CP :: You need to pass at least two out of three DomJudge
    assignments, hand in the Game Design Document, and obtain P >= 5
    to pass the course.

- The *optional assignment* grade is O.

The *final grade* is computed as F = min( 0.5 × T + 0.5 × P + 0.05 ×
O, 10 ).

The *final result* of the course is:

- Passed with grade F (appropriately rounded according to the OER
  rules) if F >= 5.5 and you satisfy conditions CT and CP.

- Not passed with AANV if F >= 4.0, you passed at least one DomJudge
  assignment, but you do not satisfy the conditions CT and CP.

    * In this case you are entitled to *aanvullende toets*, to be determined per student.
    * If you need to re-submit the final programming project, that grade is a 6 maximum.

- Not passed with NVD otherwise.
